### ISSUE TITLE
Adding Aves to map show wrong expert distro

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#133]
Add "Aves" to map and it also adds an expert distribution for `Philemon diemenensis`. 

https://spatial-beta.ala.org.au/?ss=1540529864748

**Comment by adam-collins** [comment]
The 20171012 names index match for ```Philemon diemenensis``` lists it as ```taxonomicStatus:excluded``` with the ```acceptedConceptName:AVES```. https://bie.ala.org.au/ws/search?q=Philemon%20diemenensis

Expert distributions are assigned the accepted LSID determined by name matching. When adding species to the map it will include expert distributions with the same LSID. It is intentional that mapping ```AVES``` includes the distribution for ```Philemon diemenensis```.

To resolve this issue would it be appropriate to update expert distribution name matching with some criteria before assigning an LSID? e.g. ignore name matches with ```taxonomicStatus:excluded``` when the matched concept rank is family or above.

* BIE taxonomicStatus values https://bie.ala.org.au/ws/search?q=*:*&facet=true&facets=taxonomicStatus&pageSize=0

* BIE Rank counts for taxonomicStatus:excluded
https://bie.ala.org.au/ws/search?q=taxonomicStatus:excluded&facet=true&facets=rank&pageSize=0

**Comment by adam-collins** [comment]
"Philemon diemenensis" still resolves to AVES in the new names index.

Fixed manually.

**Comment by nickdos** [comment]
Still happening... see https://support.ehelp.edu.au/a/tickets/46325

@adam-collins  - User added "aves" to map but is still presented with expert distribution for _Philemon diemensensis_ and _Tansipytera galatea_:

![image](https://user-images.githubusercontent.com/532845/70404060-e6e91500-1a8c-11ea-80ff-993860153431.png)

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/c85c25f5da3eb0e8c0e722775aa31348f59df43d

**Comment by nickdos** [comment]
Looks good - moving to ready for cab.
